### ISSUE TITLE
Known Issue: Some Pal Skills show up as Unknown

### ISSUE THREAD

**Issue by EternalWraith** [EternalWraith/PalEdit#1]
If you find any, post them here and let me know so that I can add them in. Not all of the codenames for Skills are/were known; and some may be incorrect if I guessed what the codename was based on other codenames.

**Comment by SorueGH** [comment]
Skill 'Hooligan' is missing and Skill 'Lucky' is broken and acts as if it has no effect at all once in game.

**Comment by EternalWraith** [comment]
> Skills - Hooligan, Sadist, Conceited, and Masochist are missing and Skill - Lucky is broken, and acts as if it has no effect at all once in game.

Can you elaborate on Lucky having no effect in game? Like, not giving the stat bonuses or not making the creatures bigger?

**Comment by EternalWraith** [comment]
Just rolled out an update, this should be fixed now. Thanks for your help. :)
