### ISSUE TITLE
[Request] Edit Humans

### ISSUE THREAD

**Issue by Tamamo-no-Bae** [EternalWraith/PalEdit#100]
I captured a cute Human but her stats are bad and she can only punch.
I was hoping I could have improved her stats and given her some nice passives and abilities, any chance you can add rudimentary support for editing humans?

The Human in question was: "Mercenary With a Wounded Knee"

**Comment by EternalWraith** [comment]
At the moment, editing Humans creates a plephora of issues within the editor. We will be adding the rest of the Human information to the project later in 0.6's minor updates.

**Comment by Tamamo-no-Bae** [comment]
Looking forward to it!

**Comment by EternalWraith** [comment]
Extra Human data has been added. Proper Human editing is coming in v0.8
