### ISSUE TITLE
[Request] Unlock All Learnable Skills

### ISSUE THREAD

**Issue by krulci** [EternalWraith/PalEdit#101]
As described, would like a feature to unlock a Pal's all learnable skills.
The current status of PalEdit allows equipment of skills; however, skills are actually not learned.
If you for instance, click or would like to switch order of skills in game or remove it (by clicking right click), you would loss the skills equipped.

**Comment by trzhongty** [comment]
The lost skill bug is just awful.
Hopefully, the ability to edit the list of replaceable skills can be added to save lost skills.

**Comment by EternalWraith** [comment]
This has been made into a feature
