### ISSUE TITLE
Pal editing issue

### ISSUE THREAD

**Issue by Meapster1337** [EternalWraith/PalEdit#104]
I have a world that I do co-op on with 2 of my friends and I used paledit on it to make a few of our pals have the best passives for mining and I secretly made one of mine have the best passives for damage via the presets
When in game I noticed that tons of my other pals also had the max damage passive preset applied to them when I only applied it to the one pal and both of my friends also had some of their pals in their box have those passives too.

I tested it a few times whether using the preset button or manually selecting the passives myself and every time without fail, its applying those passives to multiple pals even when I only edit one pal's passives

**Comment by Meapster1337** [comment]
I think I may of found the issue
whenever adding passives to any pal that was caught/hatched from an egg and had no passives attached to it, every pal in the file that also has no passives, gets the passives that you have chosen

**Comment by KrisCris** [comment]
It should have already been fixed on the latest version?

**Comment by Meapster1337** [comment]
ah Ill try the new versions now I didn't notice there was an update, I still have version v0.5.5 installed
