### ISSUE TITLE
Not working after the first time

### ISSUE THREAD

**Issue by Contralitary** [EternalWraith/PalEdit#105]
Hi, 

I tried the tool and it worked perfectly for the first time with all pals shown. I played for a while and thought of using the tool another time, but after loading the level.sav file, only a few tower boss pals that I caught appeared. 

Everything went fine in the game so the game saves should not have problems. Here is my level.sav file: 

https://drive.google.com/file/d/18f_0pkToNETYC3RS1YReZbRTa7-iHmC-/edit

I tested several times later on and found that, besides the tower bosses that I caught, only the pals I caught the last time I played the game will appear in PalEdit. 

Could anyone help me see what is wrong? Appreciate your help!

**Comment by Contralitary** [comment]
I tested several times and found that, besides the tower bosses that I caught, only the pals I caught the last time I played the game will appear in PalEdit.

**Comment by Yamato-X** [comment]
As a side note, the issue only appears in 0.6.1. Once the issue occurs, the newly captured pal will not appear in the list after running the program.
