### ISSUE TITLE
Higher current HP than max HP on some pals with the added scaling data causes pals to sleep forever

### ISSUE THREAD

**Issue by NoctLion** [EternalWraith/PalEdit#106]
I don't know if it's just on my file but upon testing with the added scaling data breaks a lot of Pals showing higher current hp than their max hp, said pals also won't do any work and sleep forever once they do so when night time comes and will do so until their hp is lowered. After lowering their hp through any means such as combat, using the PalEdit again will break their current hp once more.

**Comment by EternalWraith** [comment]
This should be fixed now, I believe
