### ISSUE TITLE
Cannot assign skill Divine Disaster

### ISSUE THREAD

**Issue by WindedHero** [EternalWraith/PalEdit#107]
Choosing Divine Disaster on Victor & Shadowbeak (or any other pal) sets skill slot to "None". Unrelated Pal edits seem to have removed this existing ability from my Victor & Shadowbeak.

**Comment by WindedHero** [comment]
I see in source, attacks.json Line 171 it is "exclusive" to BlackGriffon. However, cheesed bosses also have these exclusive moves.
Recommend edits adding bosses to exclusive moves for the following pals:
Axel & Orserk
Lily & Lyleen
Marus & Faleris
Victor & Shadowbeak
Zoe & Grizzbolt

**Comment by R-Josef** [comment]
> I see in source, attacks.json Line 171 it is "exclusive" to BlackGriffon. However, cheesed bosses also have these exclusive moves. Recommend edits adding bosses to exclusive moves for the following pals: Axel & Orserk Lily & Lyleen Marus & Faleris Victor & Shadowbeak Zoe & Grizzbolt

Same problem, and after you use this PalEdit and save Level.sav file, all these bosses will lose their exclusive moves.
