### ISSUE TITLE
[Request] Rename pals

### ISSUE THREAD

**Issue by WindedHero** [EternalWraith/PalEdit#108]
Would like to see this feature!

**Comment by WindedHero** [comment]
I see in source, attacks.json Line 171 it is "exclusive" to BlackGriffon. However, cheesed bosses also have these exclusive moves. 
Recommend edits adding bosses to exclusive moves for the following pals:
Axel & Orserk
Lily & Lyleen
Marus & Faleris
Victor & Shadowbeak
Zoe & Grizzbolt

**Comment by EternalWraith** [comment]
Planned for v0.9
