### ISSUE TITLE
[Bug v0.6.1] The skill Dark Laser can't be assigned to Dark pals

### ISSUE THREAD

**Issue by NeitherMeNorYou** [EternalWraith/PalEdit#111]
The title says it all, tried to apply Dark Laser to a couple pals so I wouldn't have to farm the corresponding skill fruits, and apparently that doesn't work. When selecting the skill it simply fills the slot with "None".

However this only happens with Dark typed pals, all other type pals appear to be able to learn it in the editor just fine.

This happens on v0.6.1.

**Comment by EternalWraith** [comment]
This should be fixed now
