### ISSUE TITLE
Generation

### ISSUE THREAD

**Issue by MrMatticus** [EternalWraith/PalEdit#13]
Hey eternal. Just wondering if you've got any plans to add the ability to generate Pals into our Palbox?

Edit: Just thought of it. What about also adding condenser levels and statue upgrades?

**Comment by EternalWraith** [comment]
I do have plans to do that, and condenser levels and statue upgrades. It's still a WIP and as we move towards the v1.0 release all of this will get added :)

**Comment by MrMatticus** [comment]
Awesome! Thanks for the heads up :)
