### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Soulivan71** [EternalWraith/PalEdit#138]
I dl 0.7, where I can find the .json with all my pal ?
With dump button in previous version, the app create a .json
Is it possible to do it with new version ?
And edit .json, then save by clicking on "Save Change To File"

**Comment by Netys** [comment]
Looks like no, new version can not export/import pals, it can only make a copy of pal in the same save. No more moving pals to other saves.

**Comment by Soulivan71** [comment]
Yes, im waiting for owner answer, to know if he is gonna add again or not

**Comment by Soulivan71** [comment]
Thx u !
