### ISSUE TITLE
Unable to open the JSON sav

### ISSUE THREAD

**Issue by Kotawolf** [EternalWraith/PalEdit#15]
Using the v0.2 version.

have tried to use the convert a couple of times. 
I can load the JSON files in Notepad ++ and it is there.
I tried to load it in the Edit, and it just sits...  "Loading save, please be patient"

The save is fresh from today so only about 30 min of game time. 
Used the palworld-save-tools-windows-v0.13.0.zip to do the convert.
The JSON file is about 156MB in size.

Steam version of the game.

**Comment by averon420** [comment]
used the same versions as you and it works for me. 
is your `Level.sav` file okay?
are you able to load the file with your server and can you connect?

**Comment by Kotawolf** [comment]
Yes

**Comment by EternalWraith** [comment]
There has been an update released in the last few minutes, v0.3; try to use this and decompile your save with the new built-in decompiler (no longer need SaveTools)

**Comment by Kotawolf** [comment]
New version works, granted Windows 11 screams about Virus, just tell Windows to Allow the file and it works fine.
