### ISSUE TITLE
I'm going to try it after downloading it, but there's a problem

### ISSUE THREAD

**Issue by 7dmlwd** [EternalWraith/PalEdit#16]
Can you tell me how to use it in detail? What file should I import in the load save, edit it, and save it? I'm so sorry. Thank you

**Comment by EternalWraith** [comment]
Use Converter menu to convert your `Level.sav` file to `Level.sav.json` and PalEdit will load in the information
Then when you're done editing, use the File menu to Save Changes; select the `Level.sav.json` file when you do this
Then use the Converter menu to convert your `Level.sav.json` file _back_ to `Level.sav`; and put the `Level.sav` in your save folder

Saves are located at `%LocalAppData%\Pal\Saved\SaveGames`
