### ISSUE TITLE
Some Pal's Passive Doesn't Change.

### ISSUE THREAD

**Issue by Nipaoni** [EternalWraith/PalEdit#17]
It seems some creatures doesn't change regardless of the creature type.

I uploaded the sav file. Is it possible to check it? Creatures that can't be used have Useless nickname.

[Backup Sav.zip](https://github.com/EternalWraith/PalEdit/files/14073214/Backup.Sav.zip)

-Mods I'm using.

[Uma Musume - Mihono Bourbon](https://www.nexusmods.com/palworld/mods/111)
[Uma Musume Matikanetannhauser (Facial and Mouth Expression Support)](https://www.nexusmods.com/palworld/mods/122)

**Comment by EternalWraith** [comment]
Could you elaborate on what you mean? Like the skills don't change? Or the Partner Skill?

**Comment by Nipaoni** [comment]
> Could you elaborate on what you mean? Like the skills don't change? Or the Partner Skill?

Skills (llike Legend/Lucky) doesn't change, not partner skill. 

Edit skill is Success, Convert Success, But in-game Some creatures' skills disappear completely.
Not all creatures, but certain creatures occur regardless of type.

**Comment by EternalWraith** [comment]
Can you check again to see if it is fixed now? We just released the v0.4 update with a lot of bug fixes.

**Comment by Nipaoni** [comment]
> Can you check again to see if it is fixed now? We just released the v0.4 update with a lot of bug fixes.

The problem was resolved in version 0.4. thank you
