### ISSUE TITLE
anubis not detected in paledit

### ISSUE THREAD

**Issue by ggnoobez** [EternalWraith/PalEdit#25]
for whatever reason, anubis isn't detected tho there might be others as well but from what i checked he doesn't show up.

**Comment by EternalWraith** [comment]
This should be fixed in the latest update; let me know

**Comment by Minoslo** [comment]
Same problem here. I don't know exactly why but, at some point it detects Anubis when I was tangling with the editor. Then, I made a mistake and I went back loading my backup so now, here I am with the same problem. The goobis is not in the list.
Just in case it is related, all the pals that I sold to the blackmarketeer ( that I captured for my base) still in the editor list.

**Comment by ggnoobez** [comment]
> This should be fixed in the latest update; let me know

tried out 0.4.2  anubis still not being listed in the list

**Comment by EternalWraith** [comment]
Should be listed now in 0.4.6

**Comment by Minoslo** [comment]
For me, the problem has been solved. Anubis is now detected correctly in the editor.
Thank you very much sir
