### ISSUE TITLE
Partner skill level become 0

### ISSUE THREAD

**Issue by bupjae** [EternalWraith/PalEdit#27]
Reproduce:

1) Convert Save to Json - Level.sav
2) Save Changes - Level.sav.json (without modifying any pal data)
3) Convert Json to Save - Level.sav.json

All pals I have become Partner skill Level 0.

For reference,
"Level_before.sav" is the original save file.
"Level_after.sav" is the modified save file by PalEdit.

[BF53333A4EADE7B865FBAE86F9024E8E.zip](https://github.com/EternalWraith/PalEdit/files/14076226/BF53333A4EADE7B865FBAE86F9024E8E.zip)

**Comment by Nipaoni** [comment]
same

**Comment by somebirby** [comment]
Same here.
Anyone know where that value is storing in the file, so I can quickly fix my save?

**Comment by averon420** [comment]
Should be fixed with #0.431

**Comment by therysin** [comment]
> Should be fixed with #0.431

Would this repair any saves done with the previous version?

**Comment by averon420** [comment]
> > Should be fixed with #0.431
> 
> Would this repair any saves done with the previous version?
You can already repair it. Just set rank to 1 and back to 0 for each corrupted pal.

**Comment by averon420** [comment]
@therysin alright. I changed something, so all your pals get auto fixed with the v0.44

**Comment by averon420** [comment]
If someone wants to give v.044 a try. Download current source and overwrite it with:
[PalEdit.py](https://github.com/EternalWraith/PalEdit/blob/de4a0441c1e6e6e28cd4a5310240512bdcb52c7e/PalEdit.py)
[PalInfo.py](https://github.com/EternalWraith/PalEdit/blob/de4a0441c1e6e6e28cd4a5310240512bdcb52c7e/PalInfo.py)

**Comment by therysin** [comment]
Thanks much <3

**Comment by averon420** [comment]
> Thanks much <3

Welcome, drop some feedback please about your issues.

**Comment by Nipaoni** [comment]
Doesn't change. Rank up cost is still 8. and partner skill change 0. 

Current source / overwrite PalEdit.py, Pallinfo.py

**Comment by averon420** [comment]
can you upload your level.sav and name me one pal with this issue? If you got multiple of the same species, please add a nickname like Buggedpal or smh.

**Comment by therysin** [comment]
Confirming it works to change the partner skill to level 1, however the rank is 1 star (the partner skill is level 1 at zero stars). Also confirming that the partner skill works as it's supposed to (pals drop stuff when assigned to ranch).

**Comment by averon420** [comment]
> Confirming it works to change the partner skill to level 1, however the rank is 1 star (the partner skill is level 1 at zero stars). Also confirming that the partner skill works as it's supposed to (pals drop stuff when assigned to ranch).

Don't quite understand that.
> 
> Also, in the previous version just want to point out that every pal was corrupted, not just ones that you edit.

Yh, that makes sense. Its a technical thingy. But v0.44 should fix every single pal. Did that work?

**Comment by therysin** [comment]
> > Confirming it works to change the partner skill to level 1, however the rank is 1 star (the partner skill is level 1 at zero stars). Also confirming that the partner skill works as it's supposed to (pals drop stuff when assigned to ranch).
> 
> Don't quite understand that.
> 
> > Also, in the previous version just want to point out that every pal was corrupted, not just ones that you edit.
> 
> Yh, that makes sense. Its a technical thingy. But v0.44 should fix every single pal. Did that work?

![image](https://github.com/EternalWraith/PalEdit/assets/7350389/1ee136b1-597c-443d-9f99-4eea03f63039)
Hopefully you can see what I mean in the image above. The star rank of the pal is zero, but the partner skill is at level 1. Your fix assigns a star rank of 1 to every pal(when the star rank should remain at zero but the partner skill should be at level 1).

Yeah the fix was applied to every pal.

**Comment by therysin** [comment]
Deleted my previous post, mistakes were made on my end.

Confirming that the partner skill rank restored to level 1 for all pals.

Thanks.

**Comment by Nipaoni** [comment]
[Backup Sav.zip](https://github.com/EternalWraith/PalEdit/files/14079094/Backup.Sav.zip)

Two file. Original and PalEdit.

The pal I fixed(only edit 1 pal) add a nickname Buggedpal. but all creature rank up cost 8 and partner skill change to 0.

**Comment by averon420** [comment]
> [Backup Sav.zip](https://github.com/EternalWraith/PalEdit/files/14079094/Backup.Sav.zip)
> 
> Two file. Original and PalEdit.
> 
> The pal I fixed(edit 1 pal only) add a nickname Buggedpal. but all creature rank up cost 8 and partner skill change to 0. oh, and I use preset worker.

Sorry was busy with another issue, join this discord pls. https://discord.gg/tqH8NE293C

**Comment by averon420** [comment]
> Deleted my previous post, mistakes were made on my end.
> 
> Confirming that the partner skill rank was restored to level 1 for all pals.
> 
> Thanks.

great to hear, I can't delete your post. I have no mod permissions.

**Comment by LordNEWNS** [comment]
came to comment this about the pals partners skills and star level not only taking double but also not increasing. is there a way to get a notification when the fix is live?

**Comment by averon420** [comment]
> came to comment this about the pals partners skills and star level not only taking double but also not increasing. is there a way to get a notification when the fix is live?

if you want, join https://discord.gg/tqH8NE293C and test v0.45
