### ISSUE TITLE
Passive skill issue | Pals not visible in PalEdit | PalEdit show pals that are gone

### ISSUE THREAD

**Issue by BakaxDanielxsan** [EternalWraith/PalEdit#28]
v0.3.1
I have managed to edit 133/137 pals passive skills and rank, but seems like 009 Rooby, 018 Cremis, 043 Dumud and 070 Flambelle lose their 3rd and 4th passive skills.

v0.4.2
Rooby, Cremis, Dumud and Flambelle no longer shows up in PalEdit. Tried to catch multiple of those pals in case the ones in my palbox were bugged but the new ones does not show up either.

v0.4.2
6 jetragons which I have either sold or consumed in rank up still shows up in the PalEdit, but this wont be an issue when delete pal option is implemented.

**Comment by averon420** [comment]
Do you decompress the most recent level.sav, and load it? Or do you use the .pson file?

**Comment by averon420** [comment]
With 0.4+ you can just open the level.sav directly, it will convert it. But I guess @EternalWraith needs to look into this issue.

**Comment by averon420** [comment]
can you try to close the tool and delete/move current.pson for your last issue - 
I can't reproduce the issue with pals not showing up, tried it with dumud.

**Comment by averon420** [comment]
Okay. how about when you upload the level.sav? its about ~11mb. I am using the tool since very 0.1 and did not have any of those issues.

**Comment by averon420** [comment]
> [Save.zip](https://github.com/EternalWraith/PalEdit/files/14079032/Save.zip)

Please join this discord https://discord.gg/tqH8NE293C
