### ISSUE TITLE
The cost to upgrade pal's rank(mean star) is doubled at first rank up.

### ISSUE THREAD

**Issue by Nipaoni** [EternalWraith/PalEdit#29]
The number of pals needed for the first rank up(0 ->1 rank) should be 4, but is 8. 
Even if collect 8 and try rank up, they will not rank up and change the number required becomes 4. 
After that, rank up normally. 

 The newly acquired pal had a rank-up cost 4, and when I saved with PalEdit, I found that it went up to 8.

 1 -> 2 rank up seems to work normally. (needed 16 pal)
I couldn't check more rank that because I didn't have enough pal numbers.

**Comment by averon420** [comment]
**Handle this issue as closed and continue in #27 as this is the same issue.**
