### ISSUE TITLE
Editing farming pals stopped them to produce anything

### ISSUE THREAD

**Issue by xaliber** [EternalWraith/PalEdit#30]
I edited farming pals to have abilities like Artisan, Serious, and the like. But they just stopped producing anything. I edited the save again and return them without those abilities, but it still bugs. Even farming Pals who I didn't edit stop producing.

Strangely, berry producing is also affected. Pals just stopped gathering berries at all.

**Comment by rselimfirat** [comment]
I think editor somehow sets passives to Lv 0 rather than Level 1? No clue how or why it happened that way but pets I bred and caught after edit seemed to work fine.

**Comment by xaliber** [comment]
For reference, I'm attaching the save file before & after edit. A few things has happened since the edit (raids, captured new pals, etc)

[before & after edit.zip](https://github.com/EternalWraith/PalEdit/files/14076974/before.after.edit.zip)

**Comment by xaliber** [comment]
> I think editor somehow sets passives to Lv 0 rather than Level 1? No clue how or why it happened that way but pets I bred and caught after edit seemed to work fine.

**Comment by xaliber** [comment]
Oops, sorry for the above, accidentally clicked completed.

> I think editor somehow sets passives to Lv 0 rather than Level 1? No clue how or why it happened that way but pets I bred and caught after edit seemed to work fine.

Yeah you're correct. Apparently all the Pals now have Passives to level 0. Newly caught Pals don't have this issue, even though there's another edit after they have been caught. I see someone else has similar issue...  #27

**Comment by dhpancor** [comment]
Same issue here! It needs a fix, and should set all Pals with passive at 0 to level 1 to revert this.

**Comment by averon420** [comment]
Should be fixed with #31

**Comment by averon420** [comment]
**Handle this issue as closed and continue in #27 as this is the same issue.**
