### ISSUE TITLE
Unable to save changes correctly

### ISSUE THREAD

**Issue by BAKAOLC** [EternalWraith/PalEdit#33]
![image](https://github.com/EternalWraith/PalEdit/assets/35646643/2fffd7f9-73a0-462e-b493-7c7d1cc08bc3)
I have a large save that loads fine, but the save stops midway causing the save to become corrupted.
Level.sav.json is the stored file, and Level2.sav.json is the backup decompressed data. There is obviously a very abnormal gap in size between them (and the text editor will refuse to read the edited file because the file Damaged)
I don't know if it's a problem because the archive is too large or because there are characters from other languages (like Chinese characters) in the archive
Here I attach my [archived data](https://drive.google.com/file/d/1z2LZdI_91hCW6jPkHPxUtwO4IseKmJS1/view?usp=sharing), hoping to find out the problem

**Comment by averon420** [comment]
You should add more info, which versions and which tools do you use in which order. What exactly do you do?

**Comment by BAKAOLC** [comment]
I only use PalEdit v0.4.2 (I am currently unable to try a new version, I will try it later)
I simply used the options in the conversion to convert the Sav file to a JSON file, and then edited the properties of a named unit and saved the changes, which resulted in an error

**Comment by BAKAOLC** [comment]
I just tried the latest v0.4.6 and it also has this problem

> Converter: Convert save to Json → Select any Pal → Use any preset → Save changes → Get problem file3

And I just tested it again, and in my case I just had to save the changes directly after loading and it was already a corrupted file.

**Comment by averon420** [comment]
can you please join discord: https://discord.gg/EckmjNDq
I had no issues with your save - loaded and saved without any modifications.
[Level.zip](https://github.com/EternalWraith/PalEdit/files/14090077/Level.zip)

**Comment by BAKAOLC** [comment]
Of course, I'm more than willing to help.

**Comment by BAKAOLC** [comment]
great, it's solved!
