### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by MrMatticus** [EternalWraith/PalEdit#4]
When loading a sav.josn I'm getting errors for all my boxed Pals. Saying "BOSS_JetDragon" "BOSS_Anubis" and "BOSS_Umihebi_Fire" if anyone knows how to fix.

**Comment by EternalWraith** [comment]
Hey, it seems that BOSS creatures are coded differently from Normal Pals; I'll have a look at this and hopefully implement a solution by this evening.

**Comment by EternalWraith** [comment]
Just rolled out an update that seems to fix the issue, let me know if it's not working.

**Comment by MrMatticus** [comment]
That fixed it! You're awesome thank you!

**Comment by EternalWraith** [comment]
Computers do be funny like that sometimes. Is it safe to close this issue?

**Comment by MrMatticus** [comment]
Yea should be
