### ISSUE TITLE
PalEdit.exe contains Trojan

### ISSUE THREAD

**Issue by KongGal** [EternalWraith/PalEdit#41]
THIS ISSUE HAS BEEN REMOVED DUE TO MISINFORMATION

**Comment by EternalWraith** [comment]
Can you stop spreading misinformation?

**Comment by Paluto42** [comment]
Does not happen with my Windows defender(old build) , If you want to make sure the program is not harmful, pls use PyInstaller to recompile all code and check.Compiling programs with high-level languages ​​often triggers false detections in antivirus software.

**Comment by KongGal** [comment]
> Does not happen with my Windows defender(old build) , If you want to make sure the program is not harmful, pls use PyInstaller to recompile all code and check.Compiling programs with high-level languages ​​often triggers false detections in antivirus software.

Yet why isn't there any mentions of such "false positive" on the README? why he is trying to hide the evidence provided calling it misinformation? if there wan't anything to it he wouldn' deleted the evidence, close it and just be like misinformation but he would then instead spent 2 min explains why there is a "false" positive so when others check they can't just see the creator hiding things
