### ISSUE TITLE
Ver 0.4.6 detected as a virus by Windows Defender

### ISSUE THREAD

**Issue by xaliber** [EternalWraith/PalEdit#44]
Just downloaded and tried it, used it for a few mins and it's closed by itself and got removed by Windows (Windows 10).

WinDefender says it's a virus. False positive?

![image](https://github.com/EternalWraith/PalEdit/assets/22586164/f5e081f2-e7a8-44db-a616-36658cf901f6)

![image](https://github.com/EternalWraith/PalEdit/assets/22586164/2e1283eb-a981-4ba3-b3a8-4a33de2ef872)

**Comment by madcatzfight** [comment]
It is a false positive. There is already a closed issue on this.
