### ISSUE TITLE
few issues

### ISSUE THREAD

**Issue by tesquathor** [EternalWraith/PalEdit#6]
I found some of issues.

the lucky passive is not operating. (attack +15%, work speed + 15%)
 and PalEdit can't detected legend, has boss mark, and original Lucky pals(obtain on field).

**Comment by kevrlet** [comment]
In addition, Diet Lover and Workaholic (and presumably the lesser versions of them) are swapped with their negative counterparts. PAL_Sanity_Up_2 seems to be Destructive, rather than Workaholic like you'd assume.

**Comment by EternalWraith** [comment]
The Lucky fix was already rolled out; as was the Boss and Lucky Pal mark detection. Make sure you haven't downloaded an old version of the file.

**Comment by kevrlet** [comment]
Not sure if this was directed at me or not, but yeah, I downloaded the most recent (at the time of posting). Alphas and Luckies were listed, but the hunger/sanity passives were swapped compared to what is reflected ingame.
