### ISSUE TITLE
unable to load JSON file.

### ISSUE THREAD

**Issue by SilverHuskey** [EternalWraith/PalEdit#7]
So when i try to load JSON file i get this stuff in the console. I dont know what to do or how to fix it, and i have no idea how my memory isnt enough, I have 32GB of RAM and nothing else was running besides opera GX and Discord..

Python 3.12.1
"C:\Users\Aurora\Desktop\PalEdit-main\"
Opening file C:/Users/Aurora/Desktop/PalEdit-main/Level.sav
Opening file C:/Users/Aurora/Desktop/PalEdit-main/Level.sav.json
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Aurora\AppData\Local\Programs\Python\Python312-32\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Aurora\Desktop\PalEdit-main\PalEdit.py", line 98, in loadfile
    data = json.loads(f.read())
                      ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
MemoryError

**Comment by EternalWraith** [comment]
Can you try again with the new update?

**Comment by SilverHuskey** [comment]
Seems to work now yeah. Thanks.
