### ISSUE TITLE
Display Pal Custom Names

### ISSUE THREAD

**Issue by kevrlet** [EternalWraith/PalEdit#8]
I have anywhere from 1 to 15 of a given Pal, and it would be very helpful if the tool displayed the names I gave them (NickName.value in the .json file) so I know which ones I am editing, and to make it easier to find the ones I'm looking for.

**Comment by EternalWraith** [comment]
I've scheduled this for the v0.3 update alongside changing the Pals species and whether its Lucky or Boss.
