### ISSUE TITLE
Editing the traits of a pal without any preexisting traits will copy the set traits to all other pals without traits

### ISSUE THREAD

**Issue by NeitherMeNorYou** [EternalWraith/PalEdit#82]
As the title says, I've edited the traits on a pal without any previous traits. This caused all my other pals without any existing traits to then also obtain those same traits.

As an example, I had an Arsox with no traits. I edited it in new traits like Swift and Logging Foreman. I then save the file, load it into the game, and now all other pals that had no previous traits will also have Swift and Logging Foreman.

This is repeatable for me, I've tested the procedure with an older backup where I picked a different pal without traits (a Celaray in this case) and the traits then also propagated to all other pals without any traits.

Edit: Totally forgot to say, this happened with version 0.51 but I was also able to replicate this with version 0.53 just now.

**Comment by AshDevFr** [comment]
I had the same issue, unfortunately I only realized that too late so I would be losing hours if I was putting back the original save. Not a huge deal but I only wanted to fix one Pal, not 20 😅
Still a great tool, thanks
