### ISSUE TITLE
Sold tower boss stay in game files

### ISSUE THREAD

**Issue by Bolde-Swoup** [EternalWraith/PalEdit#85]
Used the tools to make the five tower bosses. Then changed my mind and sold them for 0 at the Black Marketeer. They still appear when I load my file in the tool but don't appear in my palbox.

**Comment by NoctLion** [comment]
> Add this code to remove the storage conflict pals


Is this specifically for the issue of the sold tower boss? Cause adding the code provided also deleted some caught human (merchant) pals that weren't sold cause they also appear as errors and unknown during the creation of entity when loading the save file with PalEdit.

Error occured: 'PalDealer_Desert'
Error occured: 'SalesPerson_Desert2'
Error occured: 'SalesPerson_Volcano2'
Error occured: 'PalDealer_Volcano'
Error occured: 'SalesPerson_Volcano'

The other merchants are fine such as the Black Marketeer and the most basic Wandering Merchant that sells blue Pal Sphere and Schematics and Pal Merchant that mostly sells early game pals like Chikipi/Lamball/Cattiva.
