### ISSUE TITLE
Multiple pals are impacted when modifying one's passive skills

### ISSUE THREAD

**Issue by KrisCris** [EternalWraith/PalEdit#86]
When I edit a pal's passive skill, many others are also modified.

## Video

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/YzYT-qfKV1Q/0.jpg)](https://www.youtube.com/watch?v=YzYT-qfKV1Q)

**Comment by FactoryBlack** [comment]
Already reported correctly [here](https://github.com/EternalWraith/PalEdit/issues/82)

It's not just random pals, it's only pals that have no traits already supplied.
