### ISSUE TITLE
HP IV% Not working

### ISSUE THREAD

**Issue by frame318** [EternalWraith/PalEdit#89]
I have made adjustments Atttack IV / Defenece IV / HP IV to 100  But HP has not changed.

**Comment by infinitr0us** [comment]
Same with me. I was wondering if there is anything special to do so that it will take effect...

**Comment by KrisCris** [comment]
yea, for now, you will need to go into the game and level up your pals once.

also, the unused code in the editor for calculating health (if I understood correctly) is incorrect, thankfully it is not saved back to the game save

`PalEdit::updatestats`
```
            hv = 500 + (((70 * 0.5) * l) * (1 + (h / 100)))
            self.hthstatval.config(text=math.floor(hv))
```

**Comment by KrisCris** [comment]
I just fixed it on my branch:

https://github.com/KrisCris/PalEdit/tree/add_specie_scaling_and_hp_calculation

**Comment by frame318** [comment]
thank you

**Comment by KrisCris** [comment]
I am not sure what was wrong, but it seems my code is producing a different maxHP value when the SoulBonus and CondenserBonus are leveled up.
