### ISSUE TITLE
[Collab] Multilingual support

### ISSUE THREAD

**Issue by vicrodh** [EternalWraith/PalEdit#97]
Hello, I would love to collaborate with your project.
I have created a fork of it and have started to make some modifications.
The first thing, although it is not on your list of things-to-do, is to add a layer of compatibility with Linux, so that the application can run on this operating system. (It currently works as I have been doing it so far).

Then, taking a task from your list of things to do, I have made the necessary adjustments to make the application multilingual. In my latest commit in my fork, the interface translation is working. There is still work to be done regarding the translation, for example, for the names of the skills of the Pals.

Please take a look at my fork to see if you are interested in me continuing with this task before submitting a pull request, as I have practically changed all the f-strings in PalEdit.py. 

https://github.com/vicrodh/PalEdit

![image](https://github.com/EternalWraith/PalEdit/assets/103399283/92d7dd93-2b55-4fc6-8d88-26090622165f)
![image](https://github.com/EternalWraith/PalEdit/assets/103399283/fb7ed006-25ef-4f04-bedd-fac3f9117d3a)

**Comment by EternalWraith** [comment]
Hey, could you take a look at the latest main branch push. It contains localisation for Chinese and you could use this to add support for German or any language that you speak. Create a Merge Request called "[Localisation] German".
